image: fuww/firebase

stages:
  - build
  - test
  - performance
  - clear-cache

build:
  stage: build
  image: docker:stable-git
  services:
  - docker:stable-dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - setup_docker
    - build
  only:
    - branches

codequality:
  image: docker:stable
  stage: test
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - setup_docker
    - codeclimate
  artifacts:
    paths: [codeclimate.json]

performance:
  stage: performance
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - setup_docker
    - performance
  artifacts:
    paths:
    - performance.json
    - sitespeed-results/
  only:
    refs:
      - branches
    kubernetes: active

sast:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - setup_docker
    - sast
  artifacts:
    paths: [gl-sast-report.json]

pages:
  cache:
    untracked: true
    key: ${CI_BUILD_REF_NAME}
    paths:
    - node_modules/
  stage: build
  script:
  # - apk add --no-cache bash git openssh # for alpine
  # - npm install sharp@0.17.3 #latest sharp needs newer libvips but that is not in node:8 docker image
  # - npm install -sg gatsby # -sg to keep logs short - switch to -g if you want to see errors.
  # - npm install -g firebase-tools
  # - npm install -q
  - yarn install --silent
  - yarn build
  - firebase use --token $FIREBASE_DEPLOY_KEY production
  - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY    

  # --prefix-links Needed when NOT using a custom domain instead of GitLab Pages gitlab.io
  artifacts:
    paths:
    - public
  only:
  - master

clear-cache-cloudflare:
  image: fuww/alpine-curl-ssl-jq:latest
  only:
    - master
  stage: clear-cache
  dependencies:
    - pages
  script:
    - ./clear_cache.sh
  tags:
    - docker
