image: node:latest

stages:
  - build
  - clear-cache

pages:
  cache:
    untracked: true
    key: ${CI_BUILD_REF_NAME}
    paths:
    - node_modules/
  stage: build
  script:
  # - apk add --no-cache bash git openssh # for alpine
  - npm install sharp@0.17.3 #latest sharp needs newer libvips but that is not in node:8 docker image
  - npm install -sg gatsby # -sg to keep logs short - switch to -g if you want to see errors.
  - npm install -q
  - gatsby build
  - yarn global add node-gyp
  - yarn global add firebase-tools --cache-folder ../.cache_yarn
  - firebase use --token $FIREBASE_DEPLOY_KEY production
  - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY    

  # --prefix-links Needed when NOT using a custom domain instead of GitLab Pages gitlab.io
  artifacts:
    paths:
    - public
  # only:
  # - master

clear-cache-cloudflare:
  image: fuww/alpine-curl-ssl-jq:latest
  only:
    - master
  stage: clear-cache
  dependencies:
    - pages
  script:
    - ./clear_cache.sh
  tags:
    - docker
